// template/react/src/router/routes.tsx
import { lazy } from 'react'
import { RouteObject } from 'react-router-dom'
import paths from './paths'
import Layout from '@/layout'
import Home from '@/pages/home'

const NotFound = lazy(() => import('@/pages/notFound'))

const routes: RouteObject[] = [
    {
        path: paths.root,
        element: <Layout />,
        children: [
            {
                index: true,
                element: <Home />
            }
        ]
    },
    {
        path: '*',
        element: <NotFound />
    }
]

export default routes

// template/web-app/solid/src/router/routes.ts
import { lazy } from 'solid-js'
import { RouteDefinition } from '@solidjs/router'
import * as home from './home'

const routes: RouteDefinition[] = [
    {
        path: '/',
        component: lazy(() => import('@/layout')),
        children: [...home.routes]
    },
    {
        path: '/*all',
        component: lazy(() => import('@/pages/notFound'))
    }
]
export default routes
